services:
  db:
    image: postgres:16
    container_name: taskhub-db
    environment:
      POSTGRES_DB: taskhub_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: